# Docker Compose 파일 버전
version: '3.8'

# 실행할 서비스(컨테이너) 정의
services:
  # 서비스 이름 (원하는 대로 지정 가능)
  tetris-app:
    # 빌드 설정
    build:
      # Dockerfile이 있는 위치를 지정합니다. '.'은 현재 디렉터리를 의미합니다.
      context: .
    # 컨테이너 이름을 지정합니다. (선택 사항)
    container_name: se-tetris-java

    # 컨테이너가 실행된 후 자동으로 삭제되도록 설정합니다.
    # 프로그램 실행이 끝나면 컨테이너가 남지 않아 깔끔합니다.
    restart: 'no' # 프로그램 실행 후 컨테이너를 다시 시작하지 않음

    # --- 추가된 부분 ---
    # Host PC의 DISPLAY 환경 변수를 컨테이너로 전달합니다.
    # 이렇게 하면 컨테이너가 Host의 화면(XQuartz)을 찾아 GUI를 그릴 수 있습니다.
    environment:
      - DISPLAY=${DISPLAY}