package seoultech.se.core.model;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * 🎯 Simple Lombok Test - Verify Builder Pattern Works
 */
class TestModelBuilderTest {

    @Test
    void lombokBuilderShouldWork() {
        // This should compile if Lombok is working properly
        TestModel model = TestModel.builder()
            .name("Test Name")
            .value(42)
            .build();
        
        assertThat(model.getName()).isEqualTo("Test Name");
        assertThat(model.getValue()).isEqualTo(42);
        
        // Test toString() generation
        String result = model.toString();
        assertThat(result).contains("Test Name");
        assertThat(result).contains("42");
    }
    
    @Test 
    void lombokDataShouldWork() {
        TestModel model = new TestModel();
        
        // Test setters (should be generated by @Data)
        model.setName("Data Test");
        model.setValue(100);
        
        // Test getters (should be generated by @Data)  
        assertThat(model.getName()).isEqualTo("Data Test");
        assertThat(model.getValue()).isEqualTo(100);
    }
}
